### ISSUE TITLE
Optimizar dockerfiles

### ISSUE THREAD

**Issue by leandrojdl** [PracticaDS/pdes-tp-anonymous#100]
Están muy pesados, hay que optimizarlos

**Comment by juanmottesi** [comment]
En el back se puede cambiar de node:11 a node:11-slim

**Comment by leandrojdl** [comment]
Voy a usar node:11-alpine que pesa menos que el slim (que es debian); además voy a cambiar el git clone por la descarga del master.zip; sino estamos clonando la historia al pedo
