### ISSUE TITLE
Diseño del tick y acciones en las maquinas

### ISSUE THREAD

**Issue by juanmottesi** [PracticaDS/pdes-tp-anonymous#20]
* Redux:
  * [ ] Piso
  * Maquinas
    * [ ] Transporter
    * [ ] Starter
    * [ ] Seller
    * [ ] Furnace
    * [ ] Crafter
  * [ ] Tick

**Comment by leandrojdl** [comment]
no sé pq no se cerró, creo que le pifié a la convención. Lo cierro a mano
